name: cq_policy_run

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  nightly_policy_run:
    if: github.event_name != 'schedule' || (github.event_name == 'schedule' && github.repository == 'cloudquery-policies/aws')
    strategy:
      matrix:
        dbversion: [ "postgres:latest" ]
        go: [ "1.17" ]
        platform: [ ubuntu-latest ] # can not run in macOS and widnowsOS
    runs-on: ${{ matrix.platform }}
    services:
      postgres:
        image: ${{ matrix.dbversion }}
        env:
          POSTGRES_PASSWORD: pass
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Cache CQ
        id: cache-cq-binary
        uses: actions/cache@v2
        with:
          path: cloudquery
          key: ${{ runner.os }}-${{ hashFiles('cloudquery') }}

      - name: Download Cloudquery
        if: steps.cache-cq-binary.cache-hit != 'true'
        run: |
          curl -L https://github.com/cloudquery/cloudquery/releases/latest/download/cloudquery_${OS}_x86_64 -o cloudquery
          chmod a+x cloudquery
        env:
          OS: Linux

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Policy Run
        run: |
          ./cloudquery policy fetch --config ./test/policy_cq_config.hcl --enable-console-log --fail-on-error
          ./cloudquery policy run --config ./test/policy_cq_config.hcl --enable-console-log --fail-on-error --stop-on-failure
        env:
          CQ_REATTACH_PROVIDERS: .cq_reattach
          CQ_NO_TELEMETRY: 1

      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        if: ${{ failure() }}
        env:
          SLACK_CHANNEL: oss-tests
          SLACK_COLOR: ${{ job.status }}
          SLACK_MESSAGE: 'AWS Policies - nightly run failed'
          SLACK_TITLE: AWS - nightly fetch failed
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}