name: lint
on: [push, pull_request]

jobs:
  Lint-Policies:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - run: go install github.com/hashicorp/hcl/v2/cmd/hclfmt@latest
      - name: Lint-All HCL files
        run: find . -type f -name "*.hcl" -exec $(go env GOPATH)/bin/hclfmt --require-no-change {} \;